name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=pablopupo_elasticsearch
            -Dsonar.organization=pablopupo
            -Dsonar.scm.disabled=true
            -Dsonar.coverage.exclusions=**/*
            -Dsonar.exclusions=**/test/**,**/*.js,**/*.cpp,**/*.h
            -Dsonar.java.binaries=.
